<?php
namespace ZinCelestial\Platform\Workflow\Durable;
use RuntimeException;use ZinCelestial\Platform\Workflow\WorkflowRun;use ZinCelestial\Platform\Workflow\Contracts\WorkflowRepositoryInterface;defined('ABSPATH')||exit;
final class WorkflowRunRepository implements WorkflowRepositoryInterface {private ?string $token=null;public function __construct(private \wpdb $db,private string $table,private int $site_id){$this->table=preg_replace('/[^A-Za-z0-9_]/','',$table);if($site_id<1)throw new RuntimeException('Invalid tenant scope.');}
 public function insert(WorkflowRun $r):void{$ok=$this->db->insert($this->table,['site_id'=>$this->site_id,'run_id'=>$r->id(),'payload'=>wp_json_encode($r->to_array()),'version'=>1,'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)],['%d','%s','%s','%d','%s','%s']);if($ok!==1)throw new RuntimeException('Workflow insert failed.');}
 public function save(WorkflowRun $r,int $expected):int{$next=$expected+1;$n=$this->db->query($this->db->prepare("UPDATE {$this->table} SET payload=%s,version=%d,updated_at=UTC_TIMESTAMP(6) WHERE site_id=%d AND run_id=%s AND version=%d",wp_json_encode($r->to_array()),$next,$this->site_id,$r->id(),$expected));if($n!==1)throw new RuntimeException('Concurrent workflow update detected.');return $next;}
 public function get(string $id):?WorkflowRun{$row=$this->db->get_row($this->db->prepare("SELECT payload FROM {$this->table} WHERE site_id=%d AND run_id=%s",$this->site_id,sanitize_key($id)),ARRAY_A);return $row?WorkflowRun::from_array((array)json_decode($row['payload'],true,32,JSON_THROW_ON_ERROR)):null;}
 public function claim(string $id,string $worker,int $seconds):bool{$this->token=hash('sha256',wp_generate_uuid4().$worker);$until=gmdate('Y-m-d H:i:s.u',microtime(true)+max(10,$seconds));$n=$this->db->query($this->db->prepare("UPDATE {$this->table} SET lease_owner=%s,lease_token=%s,lease_until=%s WHERE site_id=%d AND run_id=%s AND (lease_until IS NULL OR lease_until<UTC_TIMESTAMP(6))",sanitize_key($worker),$this->token,$until,$this->site_id,sanitize_key($id)));return $n===1;}
 public function heartbeat(string $id,string $worker,int $seconds):bool{if(!$this->token)return false;$until=gmdate('Y-m-d H:i:s.u',microtime(true)+max(10,$seconds));return $this->db->query($this->db->prepare("UPDATE {$this->table} SET lease_until=%s WHERE site_id=%d AND run_id=%s AND lease_owner=%s AND lease_token=%s AND lease_until>=UTC_TIMESTAMP(6)",$until,$this->site_id,sanitize_key($id),sanitize_key($worker),$this->token))===1;}
 public function release(string $id,string $worker):void{if(!$this->token)return;$this->db->query($this->db->prepare("UPDATE {$this->table} SET lease_owner=NULL,lease_token=NULL,lease_until=NULL WHERE site_id=%d AND run_id=%s AND lease_owner=%s AND lease_token=%s",$this->site_id,sanitize_key($id),sanitize_key($worker),$this->token));$this->token=null;}}
