<?php
namespace ZinCelestial\Platform\Workflow;use DomainException;defined('ABSPATH')||exit;
final class WorkflowRun {private string $status='pending_approval';private int $cursor=0;private int $attempt=0;private array $events=[];
 public function __construct(private string $id,private string $workflow_id,private int $workflow_version,private string $scope,private array $context=[],private int $created_at=0,private int $approval_expires_at=0){$this->id=sanitize_key($id);$this->workflow_id=sanitize_key($workflow_id);$this->scope=sanitize_key($scope);$this->context=self::sanitize_context($context);$this->created_at=$created_at?:time();$this->approval_expires_at=$approval_expires_at?:time()+900;$this->record('created');}
 public static function from_array(array $x):self{$r=new self($x['id'],$x['workflow_id'],(int)$x['workflow_version'],$x['scope']??'site',$x['context']??[],(int)$x['created_at'],(int)$x['approval_expires_at']);$r->status=$x['status'];$r->cursor=(int)$x['cursor'];$r->attempt=(int)($x['attempt']??0);$r->events=$x['events']??[];return $r;}
 public function to_array():array{return['id'=>$this->id,'workflow_id'=>$this->workflow_id,'workflow_version'=>$this->workflow_version,'scope'=>$this->scope,'context'=>$this->context,'created_at'=>$this->created_at,'approval_expires_at'=>$this->approval_expires_at,'status'=>$this->status,'cursor'=>$this->cursor,'attempt'=>$this->attempt,'events'=>$this->events];}
 public function id():string{return $this->id;}public function status():string{return $this->status;}public function cursor():int{return $this->cursor;}public function context():array{return $this->context;}public function attempt():int{return $this->attempt;}
 public function approve(int $actor):void{if(time()>$this->approval_expires_at)throw new DomainException('Approval expired.');$this->move('queued',['pending_approval'],['actor'=>$actor]);}
 public function start():void{$this->move('running',['queued','retrying']);$this->attempt++;}public function advance():void{if($this->status!=='running')throw new DomainException('Run is not active.');$this->cursor++;$this->record('step_completed');}public function fail(string $code):void{$this->move('failed',['running'],['code'=>sanitize_key($code)]);}public function retry():void{$this->move('retrying',['failed']);}public function compensate():void{$this->move('compensating',['failed']);}public function compensated():void{$this->move('compensated',['compensating']);}public function complete():void{$this->move('completed',['running']);}
 private function move(string $to,array $from,array $meta=[]):void{if(!in_array($this->status,$from,true))throw new DomainException('Invalid workflow transition.');$this->status=$to;$this->record($to,$meta);}private function record(string $e,array $m=[]):void{$this->events[]=['event'=>$e,'at'=>time(),'meta'=>$m];}
 private static function sanitize_context(array $c):array{$blocked=['password','token','secret','authorization','cookie'];foreach($c as $k=>$v){if(in_array(strtolower((string)$k),$blocked,true))unset($c[$k]);elseif(is_string($v))$c[$k]=sanitize_text_field($v);elseif(is_array($v))$c[$k]=self::sanitize_context($v);}return $c;}}
